# Generated by Django 3.2.12 on 2022-03-30 03:24

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.IntegerField()),
                ('profit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.IntegerField()),
                ('income', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('email', models.EmailField(max_length=256, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('pass_cache', models.CharField(max_length=256)),
                ('session_uuid', models.UUIDField(unique=True)),
                ('registration_at', models.DateTimeField(default=datetime.datetime.now)),
                ('sugar_all_time', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('last_passive_income_data', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProvidersGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.user')),
            ],
        ),
        migrations.CreateModel(
            name='AdminsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.user')),
            ],
        ),
    ]
