# Generated by Django 3.2.12 on 2022-03-29 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.IntegerField()),
                ('profit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.IntegerField()),
                ('income', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('email', models.CharField(max_length=256)),
                ('pass_cache', models.CharField(max_length=256)),
                ('session_uuid', models.CharField(max_length=256)),
                ('registration_at', models.IntegerField()),
                ('sugar_all_time', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('last_passive_income_data', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProvidersGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.provider')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.user')),
            ],
        ),
        migrations.CreateModel(
            name='AdminsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.admin')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.user')),
            ],
        ),
    ]
