# Generated by Django 4.0.3 on 2022-03-31 14:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.IntegerField()),
                ('profit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.IntegerField()),
                ('income', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('email', models.EmailField(max_length=256, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('pass_cache', models.CharField(max_length=256)),
                ('registration_at', models.IntegerField(default=time.time)),
                ('sugar_all_time', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('last_passive_income_data', models.IntegerField(default=time.time)),
                ('session_uuid', models.UUIDField(blank=True, null=True)),
                ('auth', models.UUIDField()),
                ('is_auth', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProvidersGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='djangoProject.user')),
            ],
        ),
        migrations.CreateModel(
            name='AdminsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoProject.admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='djangoProject.user')),
            ],
        ),
    ]
