# Generated by Django 3.2.12 on 2022-03-29 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsgroup',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='adminsgroup',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='providersgroup',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='providersgroup',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='AdminsGroup',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='ProvidersGroup',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
