# Generated by Django 4.0.3 on 2022-03-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth',
            field=models.UUIDField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
    ]
