# Generated by Django 3.2.12 on 2022-03-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_passive_income_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
