# Generated by Django 3.2.12 on 2022-03-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminsgroup',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='adminsgroup',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='providersgroup',
            old_name='provider_id',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='providersgroup',
            old_name='user_id',
            new_name='user',
        ),
    ]
