# Generated by Django 4.0.3 on 2022-03-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0002_alter_user_auth_alter_user_is_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
