# Generated by Django 3.2.12 on 2022-03-30 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0002_auto_20220330_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_passive_income_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='session_uuid',
            field=models.CharField(max_length=256),
        ),
    ]
