# Generated by Django 3.2.12 on 2022-03-30 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0003_auto_20220330_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='session_uuid',
        ),
    ]
