# Generated by Django 4.0.3 on 2022-03-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0004_alter_user_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
