# Generated by Django 3.2.12 on 2022-03-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0004_remove_user_session_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_uuid',
            field=models.UUIDField(blank=True, default=222),
            preserve_default=False,
        ),
    ]
