# Generated by Django 4.0.3 on 2022-04-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0005_alter_user_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='max_count',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='sugar_all_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
