# Generated by Django 3.2.12 on 2022-03-30 03:48

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0005_user_session_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_passive_income_data',
            field=models.IntegerField(default=time.time),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_at',
            field=models.IntegerField(default=time.time),
        ),
    ]
