# Generated by Django 4.0.3 on 2022-03-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0006_auto_20220330_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersgroup',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
